version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  nuto-backend:
    image: jieuniaeyo/nuto-backend:latest
    container_name: nuto-backend
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nuto

  nuto-frontend:
    image: jieuniaeyo/nuto-frontend:latest
    container_name: nuto-frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://nuto-backend:3000

