version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  nuto-backend:
    image: nuto-backend
    container_name: nuto-backend
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nuto

  nuto-frontend:
    image: nuto-frontend
    container_name: nuto-frontend
    ports:
      - "80:80"
    depends_on:
      - nuto-backend
