name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build backend image
      run: |
        docker build -t nuto-backend .

    - name: Save backend image to tar
      run: |
        docker save -o nuto-backend.tar nuto-backend

    - name: Create PEM key file
      run: |
        echo "${{ secrets.EC2_KEY_BS64 }}" | tr -d '\n' | base64 -d > key.pem
        chmod 600 key.pem

    - name: Copy backend image to EC2
      run: |
        rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" nuto-backend.tar ubuntu@${{ secrets.EC2_IP }}:~/

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo docker load -i ~/nuto-backend.tar
          cd ~/nuto-backend
          sudo docker-compose down
          sudo docker-compose up -d
          sudo rm ~/nuto-backend.tar
