name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: echo "${{ secrets.GIT_ENV }}" > .env
        
      - name: Create PEM key file
        run: |
          echo "${{ secrets.EC2_KEY_BS64 }}" | tr -d '\n' | base64 -d > key.pem
          chmod 600 key.pem

      - name: Docker image build & push
        working-directory: ${{ github.workspace }}
        run: |
          docker build -t nuto-backend .
          docker tag nuto-backend ${{ secrets.DOCKER_USERNAME }}/nuto-backend:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/nuto-backend:latest

      - name: Backup MongoDB on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "[백업 시작]"
            docker exec mongo sh -c 'exec mongodump --archive=/data/backup/backup_$(date +%F_%T).archive'
            echo "[백업 완료]"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            # DockerHub에서 프론트엔드 이미지 pull
            docker pull ${{ secrets.DOCKER_USERNAME }}/nuto-backend:latest

            docker stop nuto-backend
            docker rm nuto-backend
            
            docker run -d \
              --name nuto-backend \
              --network nuto-network \
              -p 443:443 \
              --env-file /home/ubuntu/.env \
              -v /home/ubuntu/fullchain.pem:/etc/letsencrypt/live/nuto.mirim-it-show.site/fullchain.pem:ro \
              -v /home/ubuntu/privkey.pem:/etc/letsencrypt/live/nuto.mirim-it-show.site/privkey.pem:ro \
              jieuniaeyo/nuto-backend:latest

