version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db

  backend:
    image: jieuniaeyo/nuto-backend
    container_name: nuto-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongodb
